name: Setup python and install environment
description: test

inputs:
    python-version:
      required: false
      type: string
      default: "3.11.10"
    trigger-by:
      required: false
      type: string
      default: "Other workflow file..."

runs:
  using: "composite"
  steps:
    - name: check env variable
      shell: bash
      run: |
        echo This event is trigger-by ${{inputs.trigger-by || 'push event'}}
        echo Use python-version ${{inputs.python-version || '3.11.10'}}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{inputs.python-version || '3.11.10'}}
          
    - name: Set up Python-Test Environment
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt