"""Create_Employee_Department

Revision ID: 851290e1ec88
Revises: f6412b680f3c
Create Date: 2024-12-09 22:12:30.520602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '851290e1ec88'
down_revision = 'f6412b680f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Departemt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cn_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Department_Employee_Relation',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['Departemt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['Employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'department_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Department_Employee_Relation')
    op.drop_table('Employee')
    op.drop_table('Departemt')
    # ### end Alembic commands ###
