name: Build Python

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: "3.11.10"
      trigger-by:
        required: false
        type: string
        default: "Other workflow file..."
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: check env variable
        run: |
          echo This event is trigger-by ${{inputs.trigger-by || 'push event'}}
          echo Use python-version ${{inputs.python-version || '3.11.10'}}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: ${{inputs.python-version || '3.11.10'}}
      - name: 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt