name: Python Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: "3.11.10"
      - name: 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt